### ISSUE TITLE
Is there any updates?

### ISSUE THREAD

**Issue by i2plus** [CorrM/LorAuto#1]
I can't not run correctly
![PixPin_2024-01-07_17-22-38](https://github.com/CorrM/LorAuto/assets/49112208/051b3911-49a5-409b-b29d-34040e940085)

**Comment by corrm** [comment]
Mostly its just adding `ElementalSkill` to https://github.com/CorrM/LorAuto/blob/a88021cdb235f0fd1c04408a0bc4522ef7fae4fe/src/LorAuto/Card/Model/EGameCardType.cs#L6

for now im very busy working on other project, RP are welcome.

**Comment by corrm** [comment]
@i2plus I pushed some commits to make it work again. (no idea about the strategy)

**Comment by i2plus** [comment]
> @i2plus I pushed some commits to make it work again. (no idea about the strategy)

wow, thank you, I will do some test.

**Comment by enbge** [comment]
any new updates?

**Comment by corrm** [comment]
> any new updates?

what is the problem ?

**Comment by enbge** [comment]
bot was winning games with the dedicated decks but now it cant 
we need more logic and decks i guess

**Comment by corrm** [comment]
> bot was winning games with the dedicated decks but now it cant we need more logic and decks i guess

Sorry, im busy to add more logic, is the bot still work ?
Also PR are very welcome
