### ISSUE TITLE
Unhandled exception: System.Exception: Strategy 'generic' not found.

### ISSUE THREAD

**Issue by Nhatchymt3** [CorrM/LorAuto#3]
![image](https://github.com/CorrM/LorAuto/assets/86135811/cb048caf-73df-43d7-a01a-ac50edd51967)

**Comment by Nhatchymt3** [comment]
![image](https://github.com/CorrM/LorAuto/assets/86135811/e953d5f4-18c4-4ca5-b298-6cc93e190fe3)

**Comment by corrm** [comment]
Can you give more information

**Comment by Nhatchymt3** [comment]
> Can you give more information

The error in the image occurred after the first turn and the bot only received the status as shown in the image ("UserInteractNotReady"). Even though I tried using my hand to end a few more turns, the bot still did not recognize the turn (sorry for my English). I'm quite bad so I have to use google translate)

**Comment by Nhatchymt3** [comment]
Currently there is an additional option "The path of the champion" so the bot cannot choose the starting game mode so I started manually then run the bot

**Comment by corrm** [comment]
Working on fixes, ty for report the problem

**Comment by corrm** [comment]
This should be fixed in [0.1.0](https://github.com/CorrM/LorAuto/releases/tag/0.1.0)

**Comment by Nhatchymt3** [comment]
> Working on fixes, ty for report the problem

works fine
